name: Build docs

on:
  push:
    branches:
        - dev
  pull_request:
    branches:
        - dev
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  build-docs:
    if: github.event.pull_request.draft == false || github.event_name != 'pull_request'
    permissions: 
        contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
      - name: Set up Python 🐍
        uses: actions/setup-python@v6
        with:
          python-version: 3.14
      - name: Install dependencies 🛠️
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
          python -m pip install --group docs
      - name: Build docs 📖
        run: properdocs build

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run Pa11y CI via Local Server
        run: |
          npm install -g pa11y-ci http-server
          
          # 1. Start a lightweight local server over your compiled static folder
          npx http-server site -p 8080 &
          sleep 3
          
          # 2. Run Pa11y against the local sitemap. 
          # REPLACE "https://your-actual-domain.com" with the 'site_url' from your properdocs.yml/mkdocs.yml
          npx pa11y-ci --sitemap http://localhost:8080/sitemap.xml --sitemap-find https://your-actual-domain.com --sitemap-replace http://localhost:8080

      - name: Run pa11y-ci.
        run: npm run pa11y-ci:sitemap 2>&1 | tee pa11y_output.txt
        
      - name: Read pa11y_output file.
        id: pa11y_output
        uses: juliangruber/read-file-action@v1
        with:
          path: ./pa11y_output.txt
        
      - name: Check for pa11y failures.
        if: contains(steps.pa11y_output.outputs.content, 'errno 2')
        run: |
          echo "::error::The site is failing accessibility tests. Please review the comment in the pull request or the pa11y-ci step in the workflow for details."
          exit 1

      - name: Deploy docs 🚀
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site

