name: Build docs

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  build-docs:
    if: github.event.pull_request.draft == false || github.event_name != 'pull_request'
    permissions: 
        contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
      - name: Set up Python 🐍
        uses: actions/setup-python@v6
        with:
          python-version: 3.14
      - name: Install dependencies 🛠️
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
          python -m pip install --group docs
      - name: Build docs 📖
        run: properdocs build

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'latest'

      - name: Run Pa11y CI 
        run: |
          npm install -g pa11y-ci
          npx pa11y-ci --config .pa11yci "site/**/*.html"
      - name: Deploy docs 🚀
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site

